version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: "@okta/okta-signin-widget"
    versions:
    - 5.3.0
    - 5.3.1
    - 5.3.3
    - 5.4.0
    - 5.4.1
    - 5.4.2
    - 5.4.3
    - 5.5.0
    - 5.5.1
    - 5.5.3
  - dependency-name: auth0-js
    versions:
    - 9.14.3
    - 9.15.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.11
    - 2.32.3
    - 2.32.4
    - 2.32.9
  - dependency-name: react-dom
    versions:
    - 16.14.0
